Repository theohbrothers/PSRepositoryReleaseManager, pull requests merged in 2025-04, with the labels that each got.

#193 Enhancement (ci): Re-add PowerShell Core test jobs
  .github/workflows/ci-master-pr.yml
Labels: enhancement

#192 Feature (generate): Add `VersionDate-Subject-MergesWithPRLink-CategorizedSorted` variant
  .vscode/tasks.json
  docs/samples/.vscode/tasks.submodule.json
  src/PSRepositoryReleaseManager/Public/Generate-ReleaseNotes.ps1
  src/PSRepositoryReleaseManager/generate/variants/VersionDate-Subject-MergesWithPRLink-CategorizedSorted.ps1
Labels: feature

#194 Test (ci): Add test job for PowerShell `7.5`
  .github/workflows/ci-master-pr.yml
Labels: area/tests
